### PR TITLE
Fix prompting for existing permissions

### LINKED ISSUE #348: Do not prompt for existing permissions during `wallet_enable`
Installing a snap via `wallet_enable` currently consists of three steps under the hood, presented to the user as two confirmations:
1. Adding permissions for the site to talk to the snap
2. Fetching and adding the snap to state
3. Adding the permissions for the snap to do whatever it needs to do

We currently do not prompt for step 3 if the snap already has the permissions specified in its manifest. We should also not prompt during step 1 if the installer has the permission to access the snap being requested.

This will simply require checking if the permission already exists before requesting it in the `wallet_enable` implementation, by means of a new "hook" that calls the underlying `PermissionController` method / action.

### PR DESCRIPTION
**Pull request by FrederikBolding**
Fixes #348

Removes unnecessary prompt for permissions by checking whether existing permissions satisfy the requested permissions

### CODE REVIEW

**Comment by FrederikBolding** [comment]
Not sure if this is the ideal solution yet. cc @rekmarks

File: packages/rpc-methods/src/permitted/enable.ts [hunk 1]
```diff
@@ -68,14 +69,40 @@ export type EnableWalletHooks = {
...
+  getPermissions: () => Promise<Record<string, PermissionConstraint>>;
 };
 
+function hasPermissions(
+  existingPermissions: Record<string, PermissionConstraint>,
+  requestedPermissions: RequestedPermissions,
+): boolean {
+  return Object.entries(requestedPermissions).every(
+    ([target, requestedPermission]) => {
+      if (requestedPermission.caveats) {
```
Comment (rekmarks) [inline packages/rpc-methods/src/permitted/enable.ts:86]:
```suggestion
      if (requestedPermission.caveats?.length > 0) {
```
