### PR TITLE
Run eval and fix manifest in bundler plugins

### LINKED ISSUE #451: Eval bundle in bundler plugins
We should eval the bundle in SES, like we do with `mm-snap eval`, in the Browserify, Webpack and Rollup plugins. This removes the need for the CLI when using one of the bundler plugins and results in a better developer experience.

### LINKED ISSUE #452: Automatically fix manifest when using bundler plugins
We should add an option to specify the location of the manifest file, and then automatically fix the manifest (similar to running `mm-snap manifest --fix`). This removes the need for the CLI do to this when using one of the bundler plugins, and results in a better developer experience.

E.g.
```js
const options = {
  manifest: './snap.manifest.json
};
```

### PR DESCRIPTION
**Pull request by Mrtenz**
This runs an equivalent of `mm-snap eval` and `mm-snap manifest --fix` in the bundler plugins directly.

Closes #451.
Closes #452.

### CODE REVIEW

File: packages/plugin-browserify/src/plugin.ts [hunk 1]
```diff
@@ -65,11 +126,16 @@ export class SnapsBrowserifyTransform extends Transform {
       inputSourceMap,
     });
 
-    if (result) {
-      this.push(result.code);
-    }
-
-    callback();
+    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
+    postBundle(this.#options, result!.code)
```
Comment (FrederikBolding) [inline packages/plugin-browserify/src/plugin.ts:130]: Are we sure `result` cannot be undefined in our case?

File: packages/plugin-browserify/src/__mocks__/fs.ts [hunk 2]
```diff
@@ -0,0 +1,5 @@
+import { Volume } from 'memfs';
+
+// Note: `Volume` implements most of the `fs` API, but not all.
+const volume = new Volume();
+export = { ...jest.requireActual('fs'), promises: volume.promises };
```
Comment (FrederikBolding) [inline packages/plugin-browserify/src/__mocks__/fs.ts:5]: Leave a comment that we are requiring part of fs here for Browserify reasons.

File: packages/plugin-browserify/src/plugin.ts [hunk 3]
```diff
@@ -1,9 +1,70 @@
...
+      pathUtils.dirname(options.manifestPath),
+      options.writeManifest,
+      code,
+    );
+
+    if (!options.writeManifest && errors.length > 0) {
+      console.error(`Manifest Error: The manifest is invalid.`);
+      errors.forEach((error) => console.error(`Manifest Error: ${error}`));
+
+      process.exit(1);
```
Comment (FrederikBolding) [inline packages/plugin-browserify/src/plugin.ts:54]: Is there a reason not to throw here? We do that for eval failures

File: packages/plugin-webpack/src/plugin.test.ts [hunk 4]
```diff
@@ -1,233 +1,261 @@
...
-import { createFsFromVolume, Volume } from 'memfs';
-import SnapsWebpackPlugin from './plugin';
+import webpack, { Stats, Configuration } from 'webpack';
+import { createFsFromVolume, IFs, Volume } from 'memfs';
+import { IPromisesAPI } from 'memfs/lib/promises';
+import { checkManifest, evalBundle } from '@metamask/snap-utils';
+import SnapsWebpackPlugin, { Options } from './plugin';
+import { DEFAULT_SNAP_BUNDLE, getSnapManifest } from './__test__';
+
+jest.setTimeout(10000);
```
Comment (FrederikBolding) [inline packages/plugin-webpack/src/plugin.test.ts:11]: Do these tests take this long to run?

**Review by FrederikBolding — CHANGES_REQUESTED** [review]

File: packages/plugin-webpack/src/plugin.test.ts (hunk 4 above)
Comment (Mrtenz) [reply packages/plugin-webpack/src/plugin.test.ts:11]: Nope, I added this for some debugging and forgot to remove it.

File: packages/plugin-browserify/src/plugin.ts (hunk 1 above)
Comment (Mrtenz) [reply packages/plugin-browserify/src/plugin.ts:130]: `result` is `null` if the input code is `null`. I don't think that's ever the case here. We could probably just change the function to always return something? `code` accepting `null` is leftover from the previous implementation.

File: packages/plugin-browserify/src/__test__/utils.ts [hunk 5]
```diff
@@ -0,0 +1,119 @@
...
+ * @param manifest.proposedName - The proposed name of the snap.
+ * @param manifest.initialPermissions - The initial permissions of the snap.
+ * @param manifest.shasum - The shasum of the snap.
+ * @param manifest.filePath - The path to the snap.
+ * @param manifest.packageName - The name of the snap.
+ * @param manifest.repository - The repository of the snap.
+ * @param manifest.iconPath - The path to the icon of the snap.
+ * @returns The snap manifest.
+ */
+export const getSnapManifest = ({
```
[the remark this answers is not in the document]
Comment (Mrtenz) [reply packages/plugin-browserify/src/__test__/utils.ts:53]: Yep, I'll create an issue for it.

[the remark this answers is not in the document]
Comment (Mrtenz) [reply packages/plugin-browserify/src/__test__/utils.ts:53]: #739

File: packages/plugin-browserify/src/plugin.ts (hunk 3 above)
Comment (Mrtenz) [reply packages/plugin-browserify/src/plugin.ts:54]: This is copied from the CLI, but I can change it to throw instead.

File: packages/cli/src/cmds/build/bundle.ts [hunk 6]
```diff
@@ -67,8 +67,10 @@ export function bundle(
 
     bundlerTransform?.(bundler);
 
-    bundler.plugin(plugin, {
+    bundler.plugin<Options>(plugin, {
```
[the remark this answers is not in the document]
Comment (Mrtenz) [reply packages/cli/src/cmds/build/bundle.ts:70]: There's no easy way to use Browserify for the `manifest` and `eval` command, so to keep the behaviour exactly the same between the `build` command and the other commands, it just runs those commands instead.

**Review by FrederikBolding — APPROVED** [review]
