### PR TITLE
Fix idle timeout implementation

### LINKED ISSUE #384: Fix snap idle timeout implementation
Currently the idle timeout implementation records a snap request before execution, this is a problem because the snap will then be terminated once the idle timeout is up. This effectively means that the actual request timeout is maximum `idleTimeout`.

### PR DESCRIPTION
**Pull request by FrederikBolding**
Fixes #384 

Fixes an issue with the current idle time out implementation where a snap could be terminated while executing a request. This is fixed by keeping track of how many requests are currently being executed and only updating the `lastRequest` value once the final request has finished.

### CODE REVIEW

File: packages/controllers/src/snaps/SnapController.ts [hunk 1]
```diff
@@ -631,6 +636,7 @@ export class SnapController extends BaseController<
   _stopSnapsLastRequestPastMax() {
     this._snapsRuntimeData.forEach(async (runtime, snapId) => {
       if (
+        runtime.pendingRequests === 0 &&
```
Comment (rekmarks) [inline packages/controllers/src/snaps/SnapController.ts:639]:
```suggestion
        runtime.pendingRequests === 0 &&
        // lastRequest should always be `null` here but TypeScript wants this check
```

File: packages/controllers/src/snaps/SnapController.ts [hunk 2]
```diff
@@ -631,6 +636,8 @@ export class SnapController extends BaseController<
...
+        // lastRequest should always be null here but TypeScript wants this check
```
Comment (rekmarks) [inline packages/controllers/src/snaps/SnapController.ts:640]:
```suggestion
        // lastRequest should always be set here but TypeScript wants this check
```

**Review by rekmarks — DISMISSED** [review]

**Review by rekmarks — APPROVED** [review]
